# Generated by Django 5.0.4 on 2024-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('IN PREPARATION', 'In preparation'), ('AWAITING WITHDRAW', 'Awaiting withdrawal'), ('READY FOR PICK UP', 'Ready for pick up'), ('EN ROUTE', 'En route'), ('DELIVER', 'Deliver'), ('CANCELED', 'Canceled')], max_length=25),
        ),
    ]
