# Generated by Django 5.0.4 on 2024-06-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_orderstatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
