# Generated by Django 5.0.4 on 2024-05-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20240513_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
    ]
