# Generated by Django 5.0.4 on 2024-05-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_type_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='type',
        ),
    ]
