# Generated by Django 4.2.5 on 2024-04-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='data_adicionado',
        ),
    ]
