# Generated by Django 5.0.4 on 2024-05-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, db_column='payment', on_delete=django.db.models.deletion.CASCADE, to='delivery.payment'),
        ),
    ]
