# Generated by Django 5.0.4 on 2024-05-20 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_producteditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usereditlog',
            name='altered_by',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_user', to=settings.AUTH_USER_MODEL), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usereditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
