# Generated by Django 5.0.4 on 2024-04-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_produto_wishlist_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='client',
            new_name='user',
        ),
    ]
