# Generated by Django 5.0.4 on 2024-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_producteditlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem_url',
            field=models.URLField(default='https://cdn-icons-png.freepik.com/256/5478/5478362.png?semt=ais_hybrid'),
        ),
    ]
