# Generated by Django 5.0.4 on 2024-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.payment'),
        ),
    ]
