# Generated by Django 5.0.6 on 2024-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_document_alter_deliveryrecord_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("seller applicant", "Seller applicant"),
                    ("seller", "Seller"),
                    ("deliveryman applicant", "Deliveryman applicant"),
                    ("deliveryman", "Deliveryman"),
                ],
                max_length=30,
            ),
        ),
    ]
