# Generated by Django 5.0.4 on 2024-04-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_cart_items_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount',
            new_name='quant',
        ),
    ]
