# Generated by Django 5.0.4 on 2024-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_product_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem_url',
            field=models.URLField(default="{% static 'icon.png' %}"),
        ),
    ]
