# Generated by Django 5.0.4 on 2024-06-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_clientcode_sellercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcode',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order', unique=True),
        ),
        migrations.AlterField(
            model_name='sellercode',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order', unique=True),
        ),
    ]
