# Generated by Django 5.0.4 on 2024-05-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_product_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagem_url',
            new_name='image_url',
        ),
    ]
