# Generated by Django 5.0.4 on 2024-04-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_rename_amount_cartitem_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
