# Generated by Django 5.0.4 on 2024-06-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_clientcode_order_alter_sellercode_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcode',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.order'),
        ),
        migrations.AlterField(
            model_name='sellercode',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.order'),
        ),
    ]
