# Generated by Django 5.0.4 on 2024-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_rename_imagem_url_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://img.freepik.com/vetores-gratis/caixa-de-papelao-fechada_23-2147501646.jpg?t=st=1716225238~exp=1716228838~hmac=92eccd9b59c64c15018d6bda014bb30085835dd7598b347145f68ed93a8a8a96&w=826'),
        ),
    ]
