# Generated by Django 5.0.4 on 2024-06-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_clientcode_order_alter_sellercode_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='sellercode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterModelTable(
            name='clientcode',
            table='client_code',
        ),
        migrations.AlterModelTable(
            name='sellercode',
            table='seller_code',
        ),
    ]
