# Generated by Django 5.0.4 on 2024-06-17 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_clientcode_code_alter_sellercode_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=60)),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status', to='delivery.orderstatus')),
                ('old_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_status', to='delivery.orderstatus')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_update_log',
            },
        ),
    ]
