# Generated by Django 5.0.4 on 2024-05-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_order_payment'),
        ('delivery', '0009_auto_20240503_1547'),
    ]

    operations = [
    ]
