# Generated by Django 5.0.4 on 2024-06-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_orderupdatelog_old_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.product'),
            preserve_default=False,
        ),
    ]
