# Generated by Django 5.0.4 on 2024-04-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_remove_comment_rating_billingadress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='country',
        ),
    ]
