# Generated by Django 5.0.4 on 2024-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_remove_adress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
