# Generated by Django 5.0.4 on 2024-05-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_adress_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billingadress',
            table='billing_adress',
        ),
    ]
