# Generated by Django 5.0.4 on 2024-05-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_alter_billingadress_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'recipient',
            },
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type_name',
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(choices=[('CREDIT', 'Credit card'), ('DEBIT', 'Debit card')], max_length=20),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=19)),
                ('cvv', models.IntegerField()),
                ('expiration', models.CharField(max_length=5)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.paymenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.card'),
            preserve_default=False,
        ),
    ]
