# Generated by Django 5.0.4 on 2024-05-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_recipient_rename_client_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.payment'),
        ),
    ]
